# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-02 02:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('type_of_company', models.CharField(choices=[('srv', 'service'), ('lbl', 'label'), ('oth', 'other')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=200)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('want_to_meet', models.NullBooleanField()),
                ('available_from', models.TimeField()),
                ('available_until', models.TimeField()),
                ('comments', models.TextField(max_length=200)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetings.Event')),
                ('requestee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings_meeting_requestee', to='meetings.Company')),
                ('requestor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings_meeting_requestor', to='meetings.Company')),
            ],
        ),
    ]
