# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-15 03:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='available_from',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='available_until',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='comments',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
