# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-15 05:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0002_auto_20160915_0335'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meeting',
            old_name='want_to_meet',
            new_name='requestee_wants_to_meet',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='available_from',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='available_until',
        ),
        migrations.AddField(
            model_name='meeting',
            name='requestor_wants_to_meet',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='meeting',
            name='should_meet',
            field=models.NullBooleanField(),
        ),
    ]
