# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-15 05:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0003_auto_20160915_0510'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='should_meet',
        ),
    ]
